<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\UnionResolveType;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\UnionResolveTypeInterface;
use Axtiva\FlexibleGraphql\Example\GraphQL\Model\AccountType;
use Axtiva\FlexibleGraphql\Example\GraphQL\Model\TransactionType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
final class _EntityTypeResolver implements UnionResolveTypeInterface
{
    public function __invoke($model, $context, ResolveInfo $info)
    {
        if (isset($model)) {
            switch (get_class($model)) {
                case AccountType::class:
                    return $info->schema->getType('Account');
                case TransactionType::class:
                    return $info->schema->getType('Transaction');
            }
        }
        return null;
    }
}