

declare (strict_types=1);
<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

use Axtiva\FlexibleGraphql\Resolver\Foundation\_EntitiesResolver as Base_EntitiesResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Do not edit it, it will be regenerated.
 * Representation resolver for federated graphql field Query._entities
 */
final class <?=$short_class_name?> extends Base_EntitiesResolver
{}