

declare (strict_types=1);
<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;
<?php foreach ($import_classes ?? [] as $import_class): ?>
use <?=$import_class?>;
<?php endforeach ?>

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @<?=$directive_name?><?=PHP_EOL?>
<?php if (isset($directive_description)): ?>
 * <?=$directive_description?><?=PHP_EOL?>
<?php endif ?>
 */
final class <?=$short_class_name?> implements DirectiveResolverInterface
{
    public function __invoke(callable $next, array|\ArrayAccess|null $directiveArgs, mixed $rootValue, array|\ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        throw new NotImplementedResolver('Not implemented directive resolver ' . __CLASS__);
        // FIXME example return mb_strtoupper($next($rootValue, $args, $context, $info));
    }
}
