

declare (strict_types=1);
<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
<?php foreach ($import_classes ?? [] as $import_class): ?>
use <?=$import_class?>;
<?php endforeach ?>

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for <?=$type_name?>.<?=$field_name?><?=PHP_EOL?>
<?php if (isset($field_description)): ?>
 * <?=$field_description?>
<?php endif ?>
 */
final class <?=$short_class_name?> implements ResolverInterface
{
<?php if (isset($root_value_class) || isset($field_args_class) || isset($return_class)): ?>
    /**
<?php if (isset($root_value_class)): ?>
     * @param <?=$root_value_class?> $rootValue<?=PHP_EOL?>
<?php endif ?>
<?php if (isset($field_args_class)): ?>
     * @param <?=$field_args_class?>|array<string, mixed>|\ArrayAccess<string, mixed>|null $args<?=PHP_EOL?>
<?php else: ?>
     * @param array<string, mixed>|\ArrayAccess<string, mixed>|null $args<?=PHP_EOL?>
<?php endif ?>
<?php if (isset($return_class)): ?>
     * @return <?=$return_class?><?=PHP_EOL?>
<?php endif ?>
     */
<?php endif ?>
    public function __invoke(mixed $rootValue, array|\ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        throw new NotImplementedResolver('Not implemented field resolver ' . __CLASS__);
    }
}
