

<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 * PHP representation of graphql interface <?=$interface_name?><?=PHP_EOL?>
<?php if (isset($interface_description)): ?>
 * <?=$interface_description?>
<?php endif ?>
 */
<?php if (count($implements)): ?>
interface <?=$short_class_name?> extends <?=implode(', ', $implements)?><?=PHP_EOL?>
<?php else: ?>
interface <?=$short_class_name?><?=PHP_EOL?>
<?php endif ?>
{}