<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query._entities
 * @property array<mixed> $representations 
 */
final class _EntitiesResolverArgs extends InputType
{
    protected function decorate(string $name, mixed $value): mixed
    {
        if ($value === null) {
            return null;
        }

        return $value;
    }
}
