<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query.account
 * @property string $id 
 */
final class AccountResolverArgs extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        return $value;
    }
}