<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query.dynamicSum
 * @property int $x 
 * @property int $y 
 */
final class DynamicSumResolverArgs extends InputType
{
    protected function decorate($name, $value)
    {
        
        return $value;
    }
}