<?php
/**
 * Autogenerated file by axtiva/flexible-graphql-php Do not edit it manually
 */ 
namespace Axtiva\FlexibleGraphql\Example\GraphQL;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ListOfType;
use GraphQL\Type\Definition\NonNull;
use Axtiva\FlexibleGraphql\Type\EnumType;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\CustomScalarType;
use GraphQL\Type\Definition\UnionType;
use GraphQL\Type\Definition\Directive;
use GraphQL\Type\Definition\Argument;
use GraphQL\Type\Definition\FieldDefinition;
use GraphQL\Type\Definition\InputObjectField;
use Psr\Container\ContainerInterface;
use GraphQL\Type\Schema;

class TypeRegistry
{
    private ContainerInterface $container;
    
    /**
     * @var array<string, Type>
     */
    private array $types = [];
    
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function getType(string $name): Type
    {
        return $this->types[$name] ??= $this->{$name}();
    }

    /**
     * @return object
     */
    private function getService(string $id): object
    {
        $service = $this->container->get($id);
        if (!is_object($service)) {
            throw new \RuntimeException("Service not found or invalid object: " . $id);
        }

        return $service;
    }
    
    
            public function FieldSet(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => 'FieldSet',
            'description' => NULL,

        ]);
            }
        


            public function Query(): ObjectType
            {
                return new ObjectType([
            'name' => 'Query',
            'description' => NULL,
            'fields' => fn() => ['account' => new FieldDefinition([
            'name' => 'account',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    $args = new \Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\AccountResolverArgs($args);
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\AccountResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\AccountResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => $this->Account(),
            'args' => ['id' => [
            'name' => 'id',
            'type' => fn() => Type::nonNull(Type::id()),
        ]],
        ]),'sum' => new FieldDefinition([
            'name' => 'sum',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function(mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
                        return (function (callable $next, $directiveArgs, $rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Directive\PlusXDirective');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Directive resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Directive\PlusXDirective');
    }

    return $resolver($next, $directiveArgs, $rootValue, $args, $context, $info);
})(
                        (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\SumResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\SumResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}), 
                        new \Axtiva\FlexibleGraphql\Example\GraphQL\DirectiveArgs\PlusXDirectiveArgs(['x' => '7']),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => fn() => Type::int(),
            'args' => [],
        ]),'dynamicSum' => new FieldDefinition([
            'name' => 'dynamicSum',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function(mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
                        return (function (callable $next, $directiveArgs, $rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Directive\PlusXDirective');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Directive resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Directive\PlusXDirective');
    }

    return $resolver($next, $directiveArgs, $rootValue, $args, $context, $info);
})(
                        (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    $args = new \Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\DynamicSumResolverArgs($args);
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\DynamicSumResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\DynamicSumResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}), 
                        new \Axtiva\FlexibleGraphql\Example\GraphQL\DirectiveArgs\PlusXDirectiveArgs(['x' => '4']),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => fn() => Type::int(),
            'args' => ['x' => [
            'name' => 'x',
            'type' => fn() => Type::nonNull(Type::int()),
        ],'y' => [
            'name' => 'y',
            'type' => fn() => Type::nonNull(Type::int()),
        ]],
        ]),'addHour' => new FieldDefinition([
            'name' => 'addHour',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    $args = new \Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\AddHourResolverArgs($args);
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\AddHourResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\AddHourResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => $this->DateTime(),
            'args' => ['date' => [
            'name' => 'date',
            'type' => fn() => Type::nonNull($this->DateTime()),
        ]],
        ]),'_service' => new FieldDefinition([
            'name' => '_service',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\_ServiceResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\_ServiceResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => Type::nonNull($this->_Service()),
            'args' => [],
        ]),'_entities' => new FieldDefinition([
            'name' => '_entities',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    $args = new \Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\_EntitiesResolverArgs($args);
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\_EntitiesResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query\_EntitiesResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => Type::nonNull(new ListOfType($this->_Entity())),
            'args' => ['representations' => [
            'name' => 'representations',
            'type' => fn() => Type::nonNull(new ListOfType(Type::nonNull($this->_Any()))),
        ]],
        ])],
        ]);
            }
        


            public function Node(): InterfaceType
            {
                return new InterfaceType([
            'name' => 'Node',
            'description' => NULL,
            'fields' => fn() => ['id' => new FieldDefinition([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::id()),
            'args' => [],
        ])],
        ]);
            }
        


            public function Account(): ObjectType
            {
                return new ObjectType([
            'name' => 'Account',
            'description' => NULL,
            'fields' => fn() => ['id' => new FieldDefinition([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::id()),
            'args' => [],
        ]),'number' => new FieldDefinition([
            'name' => 'number',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function(mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
                        return (function (callable $next, $directiveArgs, $rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Directive\UppercaseDirective');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Directive resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Directive\UppercaseDirective');
    }

    return $resolver($next, $directiveArgs, $rootValue, $args, $context, $info);
})(
                        \Axtiva\FlexibleGraphql\Resolver\Foundation\DefaultResolver::getInstance(), 
                        [],
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => fn() => Type::nonNull(Type::string()),
            'args' => [],
        ]),'currency' => new FieldDefinition([
            'name' => 'currency',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull($this->Currency()),
            'args' => [],
        ]),'transactions' => new FieldDefinition([
            'name' => 'transactions',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Account\TransactionsResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Account\TransactionsResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => Type::nonNull(new ListOfType(Type::nonNull($this->Transaction()))),
            'args' => [],
        ])],
        ]);
            }
        


            public function Transaction(): ObjectType
            {
                return new ObjectType([
            'name' => 'Transaction',
            'description' => NULL,
            'fields' => fn() => ['id' => new FieldDefinition([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::id()),
            'args' => [],
        ]),'amount' => new FieldDefinition([
            'name' => 'amount',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::int()),
            'args' => [],
        ]),'ups' => new FieldDefinition([
            'name' => 'ups',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::string(),
            'args' => [],
        ]),'createdAt' => new FieldDefinition([
            'name' => 'createdAt',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => $this->DateTime(),
            'args' => [],
        ]),'status' => new FieldDefinition([
            'name' => 'status',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
    
    return (function ($rootValue, $args, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Transaction\StatusResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Transaction\StatusResolver');
    }

    return $resolver($rootValue, $args, $context, $info);
})($rootValue, $args, $context, $info);
}),
            'type' => fn() => Type::nonNull($this->TransactionStatus()),
            'args' => [],
        ])],
        ]);
            }
        


            public function NamedCurrency(): ObjectType
            {
                return new ObjectType([
            'name' => 'NamedCurrency',
            'description' => NULL,
            'fields' => fn() => ['id' => new FieldDefinition([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::id()),
            'args' => [],
        ]),'name' => new FieldDefinition([
            'name' => 'name',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::string()),
            'args' => [],
        ])],
        ]);
            }
        


            public function CodedCurrency(): ObjectType
            {
                return new ObjectType([
            'name' => 'CodedCurrency',
            'description' => NULL,
            'fields' => fn() => ['id' => new FieldDefinition([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::id()),
            'args' => [],
        ]),'code' => new FieldDefinition([
            'name' => 'code',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::int()),
            'args' => [],
        ])],
        ]);
            }
        


            public function Currency(): UnionType
            {
                return new UnionType([
            'name' => 'Currency',
            'description' => NULL,
            'types' => fn() => [fn() => $this->NamedCurrency(),fn() => $this->CodedCurrency()],
            'resolveType' => (function ($model, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\UnionResolveType\CurrencyTypeResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Union resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\UnionResolveType\CurrencyTypeResolver');
    }

    return $resolver($model, $context, $info);
}),
        ]);
            }
        


            public function TransactionStatus(): EnumType
            {
                return new EnumType([
        'name' => 'TransactionStatus',
        'description' => 'TRANSACTION STATUS DOC',
        'values' => ['NEW' => [
            'name' => 'NEW', 
            'value' => 'NEW',
            'description' => NULL,
            'deprecationReason' => NULL,
            ],
'SUCCESS' => [
            'name' => 'SUCCESS', 
            'value' => 'SUCCESS',
            'description' => 'SUCCESS DOC',
            'deprecationReason' => NULL,
            ],
'FAIL' => [
            'name' => 'FAIL', 
            'value' => 'FAIL',
            'description' => NULL,
            'deprecationReason' => NULL,
            ]],
        ]);
            }
        


            public function DateTime(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => 'DateTime',
            'description' => NULL,
            'serialize' => function(mixed $value): mixed {
                $resolver = (function () {
    return $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Scalar\DateTimeScalar');
})();
                if (!$resolver instanceof \Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface) {
                    throw new \RuntimeException('Scalar resolver must implement CustomScalarResolverInterface');
                }

                return $resolver->serialize($value);
            },
            'parseValue' => function(mixed $value): mixed {
                $resolver = (function () {
    return $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Scalar\DateTimeScalar');
})();
                if (!$resolver instanceof \Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface) {
                    throw new \RuntimeException('Scalar resolver must implement CustomScalarResolverInterface');
                }

                return $resolver->parseValue($value);
            },
            'parseLiteral' => function(\GraphQL\Language\AST\Node $value, ?array $variables = null): mixed {
                $resolver = (function () {
    return $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\Scalar\DateTimeScalar');
})();
                if (!$resolver instanceof \Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface) {
                    throw new \RuntimeException('Scalar resolver must implement CustomScalarResolverInterface');
                }

                return $resolver->parseLiteral($value, $variables);
            },
        ]);
            }
        


            public function HelloWorld(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => 'HelloWorld',
            'description' => NULL,

        ]);
            }
        


            public function _FieldSet(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => '_FieldSet',
            'description' => NULL,

        ]);
            }
        


            public function _Service(): ObjectType
            {
                return new ObjectType([
            'name' => '_Service',
            'description' => NULL,
            'fields' => fn() => ['sdl' => new FieldDefinition([
            'name' => 'sdl',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => fn() => Type::nonNull(Type::string()),
            'args' => [],
        ])],
        ]);
            }
        


            public function _Entity(): UnionType
            {
                return new UnionType([
            'name' => '_Entity',
            'description' => NULL,
            'types' => fn() => [fn() => $this->Account(),fn() => $this->Transaction()],
            'resolveType' => (function ($model, $context, $info) {
    $resolver = $this->getService('Axtiva\FlexibleGraphql\Example\GraphQL\UnionResolveType\_EntityTypeResolver');
    if (!\is_callable($resolver)) {
        throw new \RuntimeException('Union resolver service is not callable: Axtiva\FlexibleGraphql\Example\GraphQL\UnionResolveType\_EntityTypeResolver');
    }

    return $resolver($model, $context, $info);
}),
        ]);
            }
        


            public function _Any(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => '_Any',
            'description' => NULL,

        ]);
            }
        


            public function link__Purpose(): EnumType
            {
                return new EnumType([
        'name' => 'link__Purpose',
        'description' => NULL,
        'values' => ['SECURITY' => [
            'name' => 'SECURITY', 
            'value' => 'SECURITY',
            'description' => '`SECURITY` features provide metadata necessary to securely resolve fields.',
            'deprecationReason' => NULL,
            ],
'EXECUTION' => [
            'name' => 'EXECUTION', 
            'value' => 'EXECUTION',
            'description' => '`EXECUTION` features provide metadata necessary for operation execution.',
            'deprecationReason' => NULL,
            ]],
        ]);
            }
        


            public function link__Import(): CustomScalarType
            {
                return new CustomScalarType([
            'name' => 'link__Import',
            'description' => NULL,

        ]);
            }
        

    public function Mutation(): ObjectType
    {
        return new ObjectType(['name' => 'Mutation', 'fields' => []]);
    }


    public function directive_uppercase(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'uppercase',
            'description' => 'CAPITALIZE ALL LETTERS IN STRING',
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_plusX(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'plusX',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [[
            'name' => 'x',
            'type' => fn() => Type::nonNull(Type::int()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_key(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'key',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ],[
            'name' => 'resolvable',
            'type' => fn() => Type::boolean(),
            'defaultValue' => true,
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_external(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'external',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_requires(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'requires',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_provides(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'provides',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_extends(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'extends',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_link(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'link',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['SCHEMA'],
            'args' => [[
            'name' => 'url',
            'type' => fn() => Type::string(),
        ],[
            'name' => 'as',
            'type' => fn() => Type::string(),
        ],[
            'name' => 'for',
            'type' => fn() => $this->link__Purpose(),
        ],[
            'name' => 'import',
            'type' => fn() => new ListOfType($this->link__Import()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_shareable(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'shareable',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_inaccessible(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'inaccessible',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION','OBJECT','INTERFACE','UNION','ARGUMENT_DEFINITION','SCALAR','ENUM','ENUM_VALUE','INPUT_OBJECT','INPUT_FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_override(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'override',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'from',
            'type' => fn() => Type::nonNull(Type::string()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_tag(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'tag',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['FIELD_DEFINITION','INTERFACE','OBJECT','UNION','ARGUMENT_DEFINITION','SCALAR','ENUM','ENUM_VALUE','INPUT_OBJECT','INPUT_FIELD_DEFINITION'],
            'args' => [[
            'name' => 'name',
            'type' => fn() => Type::nonNull(Type::string()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__tag(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__tag',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['FIELD_DEFINITION','INTERFACE','OBJECT','UNION','ARGUMENT_DEFINITION','SCALAR','ENUM','ENUM_VALUE','INPUT_OBJECT','INPUT_FIELD_DEFINITION'],
            'args' => [[
            'name' => 'name',
            'type' => fn() => Type::nonNull(Type::string()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__shareable(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__shareable',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__inaccessible(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__inaccessible',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION','OBJECT','INTERFACE','UNION','ARGUMENT_DEFINITION','SCALAR','ENUM','ENUM_VALUE','INPUT_OBJECT','INPUT_FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__override(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__override',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'from',
            'type' => fn() => Type::nonNull(Type::string()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__external(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__external',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__requires(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__requires',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__provides(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__provides',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__key(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__key',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [[
            'name' => 'fields',
            'type' => fn() => Type::nonNull($this->FieldSet()),
        ],[
            'name' => 'resolvable',
            'type' => fn() => Type::boolean(),
            'defaultValue' => true,
        ]],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_federation__extends(): Directive
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'federation__extends',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [],
        ]);
        }
        
        return $directive;
    }
        


    /**
     * @return array<int, Directive>
     */
    public function getDirectives(): array
    {
        return [$this->directive_uppercase(),$this->directive_plusX(),$this->directive_key(),$this->directive_external(),$this->directive_requires(),$this->directive_provides(),$this->directive_extends(),$this->directive_link(),$this->directive_shareable(),$this->directive_inaccessible(),$this->directive_override(),$this->directive_tag(),$this->directive_federation__tag(),$this->directive_federation__shareable(),$this->directive_federation__inaccessible(),$this->directive_federation__override(),$this->directive_federation__external(),$this->directive_federation__requires(),$this->directive_federation__provides(),$this->directive_federation__key(),$this->directive_federation__extends()];
    }
        

}
