<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\DirectiveArgs;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql directive args of plusX
 * @property int $x 
 */
final class PlusXDirectiveArgs extends InputType
{
    protected function decorate($name, $value)
    {
        
        return $value;
    }
}