<?php

declare(strict_types=1);

namespace Axtiva\FlexibleGraphql\Tests\Execution\Amphp;

use GraphQL\Type\Definition\FieldDefinition;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use Psr\Container\ContainerInterface;

/**
 * A minimal TypeRegistry that wraps field resolvers with AMPHP v3 async wrappers.
 * This matches the code pattern generated by TypeRegistryGeneratorBuilderAmphp.
 */
class AmphpTypeRegistry
{
    private ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    /**
     * @return object
     */
    private function getService(string $id): object
    {
        $service = $this->container->get($id);
        if (!is_object($service)) {
            throw new \RuntimeException("Service not found or invalid object: " . $id);
        }

        return $service;
    }

    public function Query(): ObjectType
    {
        return new ObjectType([
            'name' => 'Query',
            'fields' => fn() => [
                'sum' => new FieldDefinition([
                    'name' => 'sum',
                    'description' => null,
                    'deprecationReason' => null,
                    'resolve' => (function ($rootValue, $args, $context, $info) {
                        return \Amp\async((function (mixed $rootValue, array $args, mixed $context, \GraphQL\Type\Definition\ResolveInfo $info): mixed {
                            return (function ($rootValue, $args, $context, $info) {
                                $resolver = $this->getService(SumResolver::class);
                                if (!\is_callable($resolver)) {
                                    throw new \RuntimeException('Resolver service is not callable: ' . SumResolver::class);
                                }

                                return $resolver($rootValue, $args, $context, $info);
                            })($rootValue, $args, $context, $info);
                        }), $rootValue, $args, $context, $info);
                    }),
                    'type' => fn() => Type::int(),
                    'args' => [],
                ]),
            ],
        ]);
    }
}
