<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Directive;

use Axtiva\FlexibleGraphql\Example\GraphQL\DirectiveArgs\PlusXDirectiveArgs;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;
use ArrayAccess;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @plusX
 */
final class PlusXDirective implements DirectiveResolverInterface
{
    public function __invoke(callable $next, array|ArrayAccess|null $directiveArgs, mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        if (!$directiveArgs instanceof PlusXDirectiveArgs) {
            return $next($rootValue, $args, $context, $info);
        }

        return $next($rootValue, $args, $context, $info) + $directiveArgs->x;
    }
}
