<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Directive;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @uppercase
 * CAPITALIZE ALL LETTERS IN STRING
 */
final class UppercaseDirective implements DirectiveResolverInterface
{
    function __invoke(callable $next, $directiveArgs, $rootValue, $args, $context, ResolveInfo $info)
    {
        return mb_strtoupper($next($rootValue, $args, $context, $info));
    }
}