<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Resolver\Foundation\_ServiceResolver as Base_ServiceResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Do not edit it, it will be regenerated.
 * Representation resolver for federated graphql field Query._service
 */
final class _ServiceResolver extends Base_ServiceResolver
{}