<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Example\GraphQL\Model\AccountType;
use Axtiva\FlexibleGraphql\Example\GraphQL\Model\CodedCurrencyType;
use Axtiva\FlexibleGraphql\Example\GraphQL\Model\NamedCurrencyType;
use Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\AccountResolverArgs;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use ArrayAccess;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.account
 */
final class AccountResolver implements ResolverInterface
{
    public function __invoke(mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        if (!$args instanceof AccountResolverArgs) {
            return null;
        }

        $model = new AccountType();
        $model->id  = (string) $args->id;
        $model->number = 'fdasf32dsfasge3';

        $namedCurrency = new NamedCurrencyType();
        $namedCurrency->id = '32';
        $namedCurrency->name = 'DemoName';

        $codedCurrency = new CodedCurrencyType();
        $codedCurrency->id = '42';
        $codedCurrency->code = 42;

        $model->currency = rand(0,1) ? $namedCurrency : $codedCurrency;
        return $model;
    }
}
