<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\AddHourResolverArgs;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use ArrayAccess;
use DateTimeImmutable;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.addHour
 */
final class AddHourResolver implements ResolverInterface
{
    public function __invoke(mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        if (!$args instanceof AddHourResolverArgs) {
            return null;
        }

        return $args->date->add(new \DateInterval('PT1H'));
    }
}
