<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Example\GraphQL\ResolverArgs\Query\DynamicSumResolverArgs;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use ArrayAccess;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.dynamicSum
 */
final class DynamicSumResolver implements ResolverInterface
{
    public function __invoke(mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        if (!$args instanceof DynamicSumResolverArgs) {
            return 0;
        }

        return $args->x + $args->y;
    }
}
