<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\NamedCurrency;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use ArrayAccess;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for NamedCurrency.name
 */
final class NameResolver implements ResolverInterface
{
    public function __invoke(mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        return null;
    }
}
