<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Directive;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;
use ArrayAccess;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @sum
 * CAPITALIZE ALL LETTERS IN STRING
 */
final class SumDirective implements DirectiveResolverInterface
{
    public function __invoke(callable $next, array|ArrayAccess|null $directiveArgs, mixed $rootValue, array|ArrayAccess|null $args, mixed $context, ResolveInfo $info): mixed
    {
        return $next($rootValue, $args, $context, $info);
    }
}
