<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Model;

use Axtiva\FlexibleGraphql\Generator\Exception\UnknownEnumValue;
use Axtiva\FlexibleGraphql\Type\EnumInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 * PHP representation of graphql enum link__Purpose
 */
final class link__PurposeEnum implements EnumInterface
{
    /**
     * `SECURITY` features provide metadata necessary to securely resolve fields.
     */
    public const SECURITY = 'SECURITY';
    /**
     * `EXECUTION` features provide metadata necessary for operation execution.
     */
    public const EXECUTION = 'EXECUTION';
    public string $value;
    private static array $map = [
        self::SECURITY => true,
        self::EXECUTION => true,
    ];

    public function __construct($value)
    {
        if (!isset(self::$map[$value])) {
            throw new UnknownEnumValue(__CLASS__, $value);
        }
        $this->value = $value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}