<?php

namespace Axtiva\FlexibleGraphql\Example\GraphQL\Model;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 * PHP representation of graphql interface 
  */
interface NodeInterface
{}