<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Resolver\Transaction;

use Axtiva\FlexibleGraphql\Example\GraphQL\Model\TransactionStatusEnum;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Transaction.status
 */
final class StatusResolver implements ResolverInterface
{
    function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        $value = $rootValue->idStatus;
        $enum = null;
        if ($value === 0) {
            $enum = TransactionStatusEnum::NEW;
        } elseif ($value === 1) {
            $enum = TransactionStatusEnum::SUCCESS;
        } elseif ($value === 2) {
            $enum = TransactionStatusEnum::FAIL;
        }

        return $enum ? (string)(new TransactionStatusEnum($enum)) : null;
    }
}