

declare (strict_types=1);
<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

use Axtiva\FlexibleGraphql\Type\InputType;
<?php foreach ($import_classes ?? [] as $import_class): ?>
use <?=$import_class?>;
<?php endforeach ?>

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql type <?=$type_name?><?=PHP_EOL?>
<?php if (isset($type_description)): ?>
 * <?=$type_description?>
<?php endif ?>
<?php foreach ($fields ?? [] as $field): ?>
 * @property <?php if (!empty($field['type'])): ?><?=$field['type']?><?php else: ?>mixed<?php endif ?> $<?=$field['name']?><?php if ($field['is_nullable']): ?> = null<?php endif ?> <?=$field['description']?><?=PHP_EOL?>
<?php endforeach ?>
 */
final class <?=$short_class_name?> extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }
        <?php foreach ($fields ?? [] as $field): ?><?php if ($field['is_custom'] && $field['type_name']): ?>

        if ($name === '<?=$field['name']?>') {
            return new <?=$field['type_name']?>($value);
        }
        <?php endif ?><?php endforeach ?>

        return $value;
    }
}