

declare (strict_types=1);
<?php if (isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Representation;
use Axtiva\FlexibleGraphql\Resolver\FederationRepresentationResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Representation resolver for federated graphql type <?=$type_name?><?=PHP_EOL?>
 */
final class <?=$short_class_name?> implements FederationRepresentationResolverInterface
{
    public function getTypeName(): string
    {
        return '<?=$type_name?>';
    }

    public function __invoke(Representation $representation, $context, ResolveInfo $info)
    {
        throw new NotImplementedResolver('Not implemented field resolver ' . __CLASS__);
    }
}