

declare (strict_types=1);
<?php if(isset($namespace)): ?>
namespace <?=$namespace?>;
<?php endif ?>

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
<?php if(isset($type_description)): ?>
 * <?=$type_description?>
<?php endif ?>
 */
interface <?=$short_class_name?><?=PHP_EOL?>
{}