name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  php-test-7_4:
    name: phpunit 7.4
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: xdebug2
      - name: Validate composer.json
        run: composer validate --strict
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit
  php-test-7_4-with-parser-4:
    name: phpunit 7.4 with parser v4
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: xdebug2
      - name: Validate composer.json
        run: composer validate --strict
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run downgrade nikic/php-parser
        run: composer require nikic/php-parser "^4.12"
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit
  php-test-8_0:
    name: phpunit 8.0
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          coverage: xdebug
      - name: Validate composer.json
        run: composer validate --strict
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit

  php-test-8_1:
    name: phpunit 8.1
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: xdebug
      - name: Validate composer.json
        run: composer validate --strict
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit
  php-test-8_2:
    name: phpunit 8.2
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug
      - name: Validate composer.json
        run: composer validate --strict
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit