<?php

declare (strict_types=1);
namespace Axtiva\FlexibleGraphql\Example\GraphQL\Scalar;

use Axtiva\FlexibleGraphql\Resolver\TypedCustomScalarResolverInterface;
use DateTimeImmutable;
use GraphQL\Language\AST\StringValueNode;
use GraphQL\Language\AST\Node;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for scalar DateTime
 */
final class DateTimeScalar implements TypedCustomScalarResolverInterface
{
    public static function getTypeName(): string
    {
        return DateTimeImmutable::class;
    }

    public function serialize(mixed $value): mixed
    {
        if (!$value instanceof DateTimeImmutable) {
            return null;
        }

        return $value->format(DateTimeImmutable::ISO8601);
    }

    public function parseValue(mixed $value): mixed
    {
        if (!is_string($value) || $value === '') {
            return null;
        }

        return new DateTimeImmutable($value);
    }

    public function parseLiteral(Node $value, ?array $variables = null): mixed
    {
        if (!$value instanceof StringValueNode || $value->value === '') {
            return null;
        }

        return new DateTimeImmutable($value->value);
    }
}
